hoverboard_driver_node:
  ros__parameters:
    hoverboard_joint_publisher:
      type: "joint_state_controller/JointStateController"
      publish_rate: 50
      left_wheel: 'left_wheel'
      right_wheel: 'right_wheel'

    hoverboard_velocity_controller:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel: 'left_wheel'
      right_wheel: 'right_wheel'
      publish_rate: 50.0
      pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
      twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

      # Wheel geometry
      wheel_separation: 0.32
      wheel_radius: 0.0825
      wheel_separation_multiplier: 1.0
      wheel_radius_multiplier: 1.0

      # Command timeouts
      cmd_vel_timeout: 0.5

      # Frames
      base_frame_id: 'base_link'
      allow_multiple_cmd_vel_publishers: true
      odom_frame_id: 'odom'
      enable_odom_tf: true

      # Velocity and acceleration limits
      linear:
        x:
          has_velocity_limits: true
          max_velocity: 1.0
          has_acceleration_limits: true
          max_acceleration: 0.8
          has_jerk_limits: false
          max_jerk: 0.0
      angular:
        z:
          has_velocity_limits: true
          max_velocity: 6.28
          has_acceleration_limits: true
          max_acceleration: 3.14
          has_jerk_limits: true
          max_jerk: 3.14
